name: Cguerin
favicon: null
layout_spectrum: 0.48185058077797294
typography_spectrum: 0.7383024266455323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.026445016963407397
  lightness: 0.4075999849010259
  saturation: 0.95013417606242
  rhythmicContrast: 0.6384717123582959
purpose: []
